# Generated by Django 2.2.5 on 2022-07-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220705_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='langauage',
            new_name='language',
        ),
    ]
