# Generated by Django 2.2.5 on 2022-07-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20220717_0430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['created'], 'verbose_name': 'Room Type'},
        ),
    ]
